import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AudioProvider } from "../lib/audio-context";
import AudioPlayer from "../lib/audio-player";
import { SidebarProvider, SharedSidebar, HeaderNavigation } from "../lib/sidebar-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AudioProvider>
          <SidebarProvider>
            <div className="flex h-screen bg-slate-900 text-white overflow-hidden">
              <SharedSidebar />
              <div className="flex-1 flex flex-col min-w-0 w-full md:w-auto">
                <HeaderNavigation />
                <main className="flex-1 overflow-y-auto">
                  {children}
                </main>
              </div>
            </div>
            <AudioPlayer />
          </SidebarProvider>
        </AudioProvider>
      </body>
    </html>
  );
}
